apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: sqlike-doc
  labels:
    app: sqlike-doc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
  selector:
    app: sqlike-doc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: sqlike-doc
  labels:
    app: sqlike-doc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlike-doc
  template:
    metadata:
      labels:
        app: sqlike-doc
    spec:
      containers:
        - name: sqlike-doc
          image: registry-intl-vpc.ap-southeast-3.aliyuncs.com/sqlike/sqlike-doc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regsecret
      terminationGracePeriodSeconds: 60